FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.2

RUN apt-get -y update \
    && apt-get -y install gfortran python3.10 python3-pip

COPY . /

RUN python -m pip install --upgrade pip \
    && pip install --upgrade -r requirements.txt \
    && python setup.py install

# Entrypoint script
RUN chmod +x /script.sh
ENTRYPOINT [ "/script.sh" ]


